apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: myapp
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: centos/mysql-57-centos7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_USER
              value: opstree
            - name: MYSQL_PASSWORD
              value: opstree123
            - name: MYSQL_DATABASE
              value: springbootdb


