name: First Job
on:
  push:
    branches:
      - main

jobs:
  First_Workflow:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Running Commands
      run: |
        curl -IL https://google.com/
        ls -al
        pwd


