name: POC | Secret Tests

on:
  push:
  workflow_dispatch:

jobs:
  secret_test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make secrets
      run: |
        echo "test=`echo ${{ secrets.TEST }}`" >> secrets-temp.properties
        echo "jwt.public.key=`echo ${{ secrets.JWT_PUBLIC_KEY }}`" >> secrets-temp.properties
        echo "jwt.private.key=`echo ${{ secrets.JWT_PRIVATE_KEY }}`" >> secrets-temp.properties
        echo "test=`echo ${{ secrets.TEST }}`" >> secrets-temp.properties


    - name: Artifects store
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report
        path: |
          secrets-temp.properties